package co.gov.metropol.area247.repository.domain.support.enums;

/**
 * 
 * El orden de los elementos del Enum debe coincidir con el orden de los campos en el archivo csv de carga
 *
 */
public enum FormatoCamaraEnum {
	IDCAMARAINFRACCIONTEC,
	DESCCAMARA,
	CODCAMARA,
	VIGENTE,
	HORAINICIO,
	HORAFIN,
	LONGITUD,
	LATITUD,
	ALIASCAMARA,
	IPCAMARA,
	IDTIPOCAMARA,
	DESCRCAMARA,
	VALIDAGPS,
	IDZONA,
	DESCZONA,
	IDCIUDADZONA,
	DESCCIUDADZONA,
	IDTIPOVIA,
	DESCVIA,
	NUMEROVIA,
	IDLETRA,
	DESCLETRAVIA,
	IDCARDINALVIA,
	DESCCARDINALIDADVIA,
	IDTIPOVIACRUCE,
	DESCVIACRUCE,
	NUMEROVIACRUCE,
	IDLETRAVIACRUCE,
	DESCLETRAVIACRUCE,
	IDCARDINALVIACRUCE,
	DESCCARDINALIDADVIACRUCE,
	IDSECRETARIA,
	DESCSECRETARIA,
	IDCIUDAD,
	DESCCIUDAD;
}
